### ISSUE TITLE
msm-5.15 branch

### ISSUE THREAD

**Issue by konradybcio** [sonyxperiadev/vendor-qcom-opensource-bootctrl#4]
Please create a new branch, pulling https://github.com/konradybcio/vendor-qcom-opensource-bootctrl branch aosp/LA.VENDOR.13.2.0.r1

based on `LA.VENDOR.13.2.0.r1-20500-KAILUA.0`

**Comment by jerpelea** [comment]
we are based on LA.VENDOR.13.2.3.r1-01800-KAILUA.0
is there any reason why you request 2500?

**Comment by jerpelea** [comment]
aosp/LA.VENDOR.13.2.0.r1 is already available
